name: Compile YoBot Bronze (Windows)

on: push

jobs:
  echo-input:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create binary
        run: pyinstaller YoBot_Bronze.py
	  - uses: actions/upload-artifact@v2
        with:
          name: YoBot_Bronze
          path: YoBot_Bronze.exe