name: YoBot Bronze

on: [push, pull_request]

jobs:
  windows:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: PyInstaller Windows
      run: pyinstaller -D -F -n YoBot_Bronze -w "YoBot_Bronze.py"

    - uses: actions/upload-artifact@v3
      with:
        name: YoBot Bronze (Windows)
        path: dist/YoBot_Bronze.exe

  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: PyInstaller Linux
      run: pyinstaller -D -F -n YoBot_Bronze -c "YoBot_Bronze.py"

    - uses: actions/upload-artifact@v3
      with:
        name: YoBot Bronze (Linux)
        path: dist/YoBot_Bronze